const { app, BrowserWindow, ipcMain, session, protocol, shell } = require('electron');
const path = require('path');
const fs = require('fs');
const { spawn } = require('child_process');
const os = require('os');

// IPC Handlers for Shell Operations
ipcMain.handle('shell:open-file', async (event, filePath) => {
    if (fs.existsSync(filePath)) {
        shell.openPath(filePath);
        return { success: true };
    }
    return { success: false, error: 'Dosya bulunamadı' };
});

ipcMain.handle('shell:open-folder', async (event, folderPath) => {
    if (!fs.existsSync(folderPath)) {
        fs.mkdirSync(folderPath, { recursive: true });
    }
    shell.openPath(folderPath);
    return { success: true };
});

let mainWindow;
let pythonProcess;

const isDev = !app.isPackaged;

function createWindow() {
    mainWindow = new BrowserWindow({
        width: 1200,
        height: 800,
        backgroundColor: '#0a0a14',
        webPreferences: {
            nodeIntegration: true,
            contextIsolation: false,
            webviewTag: true
        },
        icon: path.join(__dirname, 'build', 'icon.png')
    });

    mainWindow.loadFile('src/index.html');

    // Open DevTools in dev mode
    // mainWindow.webContents.openDevTools();
}

function startPythonBackend() {
    let scriptPath;
    let pythonExecutable = 'python3';

    if (isDev) {
        scriptPath = path.join(__dirname, 'backend', 'server.py');
        pythonExecutable = path.join(__dirname, 'backend', 'venv', 'bin', 'python');
    } else {
        scriptPath = path.join(process.resourcesPath, 'backend', 'server.py');
        pythonExecutable = path.join(process.resourcesPath, 'backend', 'venv', 'bin', 'python');
    }

    console.log('Starting Python backend from:', scriptPath);

    pythonProcess = spawn(pythonExecutable, [scriptPath]);

    pythonProcess.stdout.on('data', (data) => {
        console.log(`Backend stdout: ${data}`);
    });

    pythonProcess.stderr.on('data', (data) => {
        console.error(`Backend stderr: ${data}`);
    });

    pythonProcess.on('close', (code) => {
        console.log(`Backend process exited with code ${code}`);
    });
}

const configDir = path.join(app.getPath('home'), '.social-video-utility');
const accountsFile = path.join(configDir, 'accounts.json');

// FRESH START: Delete all saved cookies and account data on every launch
try {
    if (fs.existsSync(configDir)) {
        const files = fs.readdirSync(configDir);
        for (const file of files) {
            const filePath = path.join(configDir, file);
            if (fs.lstatSync(filePath).isDirectory()) {
                // Skip directories for now or recursively delete
            } else {
                fs.unlinkSync(filePath);
            }
        }
        console.log('Startup cleanup: Wiped config directory contents');
    }
} catch (e) {
    console.error('Startup cleanup error:', e);
}

// Track current partition name (initial one is unique)
let currentPartition = `twitter-init-${Date.now()}`;

// Accounts Manager
const accountsManager = {
    getAccounts: () => {
        try {
            if (fs.existsSync(accountsFile)) {
                return JSON.parse(fs.readFileSync(accountsFile, 'utf8'));
            }
        } catch (e) { console.error('Error reading accounts:', e); }
        return { accounts: {}, activeAccount: null };
    },

    saveAccounts: (data) => {
        try {
            fs.writeFileSync(accountsFile, JSON.stringify(data, null, 2));
        } catch (e) { console.error('Error saving accounts:', e); }
    },

    updateAccount: (profile, cookies) => {
        const data = accountsManager.getAccounts();
        const cookieFileName = `cookies_${profile.username}.txt`;
        const cookieFilePath = path.join(configDir, cookieFileName);

        // Save cookies specific to this user
        let cookieString = '# Netscape HTTP Cookie File\n# Generated by Social Video Utility\n\n';
        cookies.forEach((cookie) => {
            const domain = cookie.domain.startsWith('.') ? cookie.domain : '.' + cookie.domain;
            cookieString += `${domain}\tTRUE\t${cookie.path}\t${cookie.secure.toString().toUpperCase()}\t${cookie.expirationDate}\t${cookie.name}\t${cookie.value}\n`;
        });
        fs.writeFileSync(cookieFilePath, cookieString);

        // Also update main cookies.txt if this is the active user (or becoming active)
        if (!data.activeAccount || data.activeAccount === profile.username) {
            fs.writeFileSync(path.join(configDir, 'cookies.txt'), cookieString);
        }

        data.accounts[profile.username] = {
            ...profile,
            cookieFile: cookieFileName,
            lastSeen: Date.now()
        };
        data.activeAccount = profile.username;
        accountsManager.saveAccounts(data);
        return data;
    },

    setActiveAccount: async (username, session) => {
        const data = accountsManager.getAccounts();
        const account = data.accounts[username];
        if (!account) return false;

        const cookiePath = path.join(configDir, account.cookieFile);
        if (!fs.existsSync(cookiePath)) return false;

        // Clear current cookies
        await session.clearStorageData({ storages: ['cookies'] });

        // Load target cookies
        const content = fs.readFileSync(cookiePath, 'utf8');
        const lines = content.split('\n');

        for (const line of lines) {
            if (line.startsWith('#') || !line.trim()) continue;
            const parts = line.split('\t');
            if (parts.length >= 7) {
                const cookie = {
                    url: 'https://' + parts[0].replace(/^\./, ''),
                    name: parts[5],
                    value: parts[6],
                    domain: parts[0],
                    path: parts[2],
                    secure: parts[3] === 'TRUE',
                    expirationDate: parseFloat(parts[4])
                };
                try {
                    await session.cookies.set(cookie);
                } catch (e) { /* ignore */ }
            }
        }

        // Update active account
        data.activeAccount = username;
        accountsManager.saveAccounts(data);

        // Sync main cookies.txt
        fs.copyFileSync(cookiePath, path.join(configDir, 'cookies.txt'));

        return true;
    }
};

ipcMain.on('get-home-path', (event) => {
    event.returnValue = app.getPath('home');
});

// Create window on ready
app.whenReady().then(() => {
    startPythonBackend();
    createWindow();

    const session = require('electron').session;

    // Track current partition name (changes on each account switch)
    let currentPartition = `twitter-${Date.now()}`;

    // Helper: load cookies from file into a given session
    async function loadCookiesIntoSession(ses, cookiePath) {
        const content = fs.readFileSync(cookiePath, 'utf8');
        const lines = content.split('\n');
        let loaded = 0;
        for (const line of lines) {
            if (line.startsWith('#') || !line.trim()) continue;
            const parts = line.split('\t');
            if (parts.length >= 7) {
                const cookie = {
                    url: 'https://' + parts[0].replace(/^\./, ''),
                    name: parts[5],
                    value: parts[6],
                    domain: parts[0],
                    path: parts[2],
                    secure: parts[3] === 'TRUE',
                };
                const exp = parseFloat(parts[4]);
                if (exp && exp > 0 && isFinite(exp)) {
                    cookie.expirationDate = exp;
                }
                try {
                    await ses.cookies.set(cookie);
                    loaded++;
                } catch (e) { /* skip invalid cookies */ }
            }
        }
        return loaded;
    }

    // Helper: set up auto-capture on a session (saves cookies from webview to disk)
    function setupAutoCaptureForSession(ses) {
        const filter = { urls: ['https://x.com/*', 'https://twitter.com/*'] };
        let saveTimeout;
        ses.webRequest.onCompleted(filter, (details) => {
            if (saveTimeout) clearTimeout(saveTimeout);
            saveTimeout = setTimeout(() => {
                ses.cookies.get({ url: 'https://x.com' })
                    .then((cookies) => {
                        if (cookies.length === 0) return;
                        let cookieString = '# Netscape HTTP Cookie File\n# Generated by Social Video Utility\n\n';
                        cookies.forEach((cookie) => {
                            const domain = cookie.domain.startsWith('.') ? cookie.domain : '.' + cookie.domain;
                            const expiry = cookie.expirationDate ? Math.floor(cookie.expirationDate) : 0;
                            cookieString += `${domain}\tTRUE\t${cookie.path}\t${cookie.secure ? 'TRUE' : 'FALSE'}\t${expiry}\t${cookie.name}\t${cookie.value}\n`;
                        });
                        fs.writeFileSync(path.join(configDir, 'cookies.txt'), cookieString);
                        console.log('Cookies auto-saved to cookies.txt');
                    }).catch((e) => console.log('Cookie save error:', e));
            }, 3000);
        });
    }

    // IPC Handlers
    ipcMain.handle('auth:get-accounts', () => {
        return accountsManager.getAccounts();
    });

    ipcMain.handle('auth:switch-account', async (event, username) => {
        console.log('Switching to account:', username);
        // Not used in the new flow, but keep for compatibility
        return false;
    });

    ipcMain.handle('auth:logout', async () => {
        const data = accountsManager.getAccounts();
        data.activeAccount = null;
        accountsManager.saveAccounts(data);
        // Generate a fresh empty partition
        currentPartition = `twitter-${Date.now()}`;
        mainWindow.webContents.send('cookies-loaded', null, currentPartition);
        return true;
    });

    ipcMain.handle('auth:update-profile', async (event, profile) => {
        // Capture cookies from whichever session is current
        try {
            const ses = session.fromPartition(currentPartition);
            const cookies = await ses.cookies.get({ url: 'https://x.com' });
            accountsManager.updateAccount(profile, cookies);
        } catch (e) {
            console.error('Failed to capture profile cookies:', e);
        }
        return true;
    });

    // Load saved account cookies into a BRAND NEW session
    ipcMain.handle('auth:load-cookies-to-session', async (event, accountName) => {
        const cookiePath = path.join(configDir, `cookies_${accountName}.txt`);
        if (!fs.existsSync(cookiePath)) {
            console.log('Cookie file not found:', cookiePath);
            return { success: false, error: 'Cookie file not found' };
        }

        console.log('Creating fresh session for account:', accountName);

        // Generate a unique partition name → completely new Chromium session
        currentPartition = `twitter-${accountName}-${Date.now()}`;
        const newSession = session.fromPartition(currentPartition);

        // Load cookies into the fresh session
        const loaded = await loadCookiesIntoSession(newSession, cookiePath);
        console.log(`Loaded ${loaded} cookies into partition: ${currentPartition}`);

        // Set up auto-capture for this new session
        setupAutoCaptureForSession(newSession);

        // Also sync cookies.txt for yt-dlp
        fs.copyFileSync(cookiePath, path.join(configDir, 'cookies.txt'));

        // Tell renderer the new partition name so it can recreate webview
        if (mainWindow) {
            mainWindow.webContents.send('cookies-loaded', accountName, currentPartition);
        }
        return { success: true, loaded, partition: currentPartition };
    });

    // Import from chrome
    ipcMain.handle('auth:import-chrome-cookies', async (event, accountName) => {
        // This is handled by the Flask backend, keep for IPC compatibility
        return { success: false, error: 'Use HTTP API' };
    });

    app.on('activate', () => {
        if (BrowserWindow.getAllWindows().length === 0) {
            createWindow();
        }
    });
});

app.on('window-all-closed', () => {
    if (process.platform !== 'darwin') {
        app.quit();
    }
});

app.on('will-quit', () => {
    if (pythonProcess) {
        pythonProcess.kill();
    }
});
